### ISSUE TITLE
Firmwareseite generiert die Links zu den neuen Bildern nicht korrekt

### ISSUE THREAD

**Issue by rubo77** [freifunk-kiel/startseite#2]
Das ist im firmware template mit `slugify: 'pretty' ` gelöst und funktioniert auch gut unter Ubuntu 15.10, aber auf dem Online server anscheinend nicht.

Ich habe temporär die firmware seite bei mir lokal generiert und dann hochgeladen in den /build/ Ordner

Wir müssen wohl jekyll auf dem server aktualisieren

**Comment by rubo77** [comment]
ev. braucht mal jekyll 3.x? siehe http://stackoverflow.com/questions/35856102/slugify-not-working-in-jekyll-pages

**Comment by wklaebe** [comment]
"aptitude purge jekyll", "gem install nokogiri json jekyll", "aptitude install ruby-dev", "gem install nokogiri json jekyll", "jekyll build" - geht jetzt.
